//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubComments
    {
        public int Id { get; set; }
        public int postId { get; set; }
        public string comment { get; set; }
        public int authorId { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
    }
}
