//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewClub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public int categoryId { get; set; }
        public int authorId { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string categoryName { get; set; }
    }
}
